###test get
GET http://localhost:8000/api/v1/task

### POST method

POST http://localhost:8000/api/v1/task
Content-Type: application/json


{
    "task":"shooting ",
    "hr":2,
    "type":"entry"
}

### patch
PATCH http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id":"64850e72f653eb2bdf32a062",
    "type":"bad"
}

### Delete

DELETE http://localhost:8000/api/v1/task/64850e66f653eb2bdf32a060

